import os
print("="*70)
print("EMERSON ACTIVITY AUTOMATION - PHASE 1")
print("="*70)
print("\nConfiguration:")
print(f"  Emerson Email: {os.getenv('EMERSON_EMAIL')}")
print(f"  Your Email: {os.getenv('YOUR_EMAIL')}")
print(f"  Google API Key: {os.getenv('GOOGLE_API_KEY')[:20]}...")
print(f"  Monday Token: {os.getenv('MONDAY_API_TOKEN')[:20]}...")
print("\n✓ Secrets loaded successfully!")
print("✓ Automation ready to deploy")
